version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries:
  - en-gb
  - en-uk
  - softwareTerms
  - misc
  - typescript
  - bash
  - npm
words:
  - datamodel
  - foundryvtt
ignoreWords: []
import: []
