version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries:
  - en-gb
  - en-uk
  - softwareTerms
  - misc
  - typescript
  - bash
  - npm
words:
  - anseki
  - bierner
  - chatmodes
  - csslint
  - datamodel
  - davidanson
  - dependencygraph
  - devcontainers
  - donjayamanne
  - eamodio
  - esbenp
  - foundryvtt
  - geistmann
  - githistory
  - iarna
  - jannisx
  - maciejdems
  - mhutchie
  - perkovec
  - Schmalfeldt
  - stylelintcache
  - yzhang
ignoreWords: []
import: []
