# WIP: Logging Configuration

logfiles:
  directory: ./.log

loggingLevels:
  error: 0
  warn: 1
  info: 2
  verbose: 3
  debug: 4

console:
  defaultLevel: info
  format:
    error: '{module} | {message} (error code: {code})'
    warn: '{module} | {message} '
    info: '{module} | {message} '
    verbose: '{module} | {timestamp} | {message} '
    debug: '{module} | {timestamp} | {message} | {meta}'
  toConsole: true
  timestamp: true # If false, '| {timestamp} |' is omitted
  timestampFormat: 'YYYY-MM-DD HH:mm:ss'
  colorize: ['error', 'warn']

file:
  defaultLevel: debug
  format: '{timestamp} [{level}] {message}'
  toConsole: false
  timestamp: true # If false, '| {timestamp} |' is omitted
  timestampFormat: 'YYYY-MM-DD HH:mm:ss'
  colorize: ['error', 'warn', 'debug'] # Only applies if toConsole is true
  maxSize: 10485760 # 10 MB
  maxFiles: 5

json:
  defaultLevel: debug
  format: json
  timestamp: true # If false, 'timestamp' field is omitted
  timestampFormat: 'YYYY-MM-DD HH:mm:ss'
  toConsole: false
  colorize: ['error', 'warn', 'debug'] # Only applies if toConsole is true
  maxSize: 10485760 # 10 MB
  maxFiles: 5
