# file: occlusion.yaml
# description: Configuration constants for occlusion handling in Foundry VTT
# path: src/config/constants/occlusion.yaml

## Configuration for the OcclusionHandler
occlusionHandler:
  # Events (Foundry VTT hooks) that trigger visibility refresh.
  # The order matters as a buffer is used to avoid multiple refreshes in quick succession.
  triggeringEvents:
    visibilityRefresh: true
    sightRefresh: true
    refreshTile: true
    refreshToken: false
    refreshWall: false
