name: Cleanup Vitest Artifacts

on:
  workflow_run:
    workflows: ["CI Checks"]
    types:
      - completed

jobs:
  cleanup:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Remove Vitest coverage artifacts
      run: |
        rm -rf coverage
        rm -rf .vitest
